# Generated by Django 5.2 on 2025-05-05 06:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="management",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="photo"
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
